axon7: Remove unused vendor_framework_compatibility_matrix due to conflict error
Error: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.qti.hardware.iop@1.0::IIop/default